### PR TITLE
chore: update the description

### PR DESCRIPTION
**Pull request by pahud**
Update the package description.

Fixes #

<a href="https://gitpod.io/#https://github.com/pahud/cdk-remote-stack/pull/430"></a>

### CODE REVIEW

**Comment by pahud** [comment]
Hi @alexpulver 

What do you think about it? This package now has two primary features:

1. Get outputs from cross-region cloudformation stacks.
2. Get SSM parameter store values used from cross-region cloudformation stacks.

Thoughts?

**Comment by alexpulver** [comment]
Looks great!

**Comment by alexpulver** [comment]
@pahud just making sure you saw my comment above - can you please merge this?

**Comment by pahud** [comment]
> @pahud just making sure you saw my comment above - can you please merge this?

sorry for the delay during the weekend. Let's get it merged now!

**Comment by alexpulver** [comment]
Oh no, weekend is not part of the delay, it's part of lead time! :D Thank you :)

**Pull request merged**
